const ProjectsActionTypes = {
    GET_PROJECTS : 'GET_PROJECTS',
    SET_PROJECTS: 'SET_PROJECTS',
    SET_SKILLS_FILTER: 'SET_SKILLS_FILTER',
    ADD_SKILL_FILTER: 'ADD_SKILL_FILTER',
    REMOVE_SKILL_FILTER: 'REMOVE_SKILL_FILTER',
    CLEAR_SKILL_FILTER: 'CLEAR_SKILL_FILTER',
    SET_LOADING: 'SET_LOADING'
};

export default ProjectsActionTypes;